export const Types = {
  ADDARTISTID: "ADDARTISTID",
  ADDTOPTRACKS: "ADDTOPTRACKS",
  ADDRECOMMENDEDARTISTS: "ADDRECOMMENDEDARTISTS",
  ADDALBUMID: "ADDALBUMID",
  ADDURI: "ADDURI",
  ADDSEARCH: "ADDSEARCH",
};
